### ISSUE TITLE
thoughts on Reentrancy Attacks and .transfer()

### ISSUE THREAD

**Issue by tesla809** [MatricksDeCoder/Fojini-DEX#2]
Regarding, 
1. Reentrancy Attacks
"The process of sending ether to an address requires the contract to submit an external call, this can lead to hijack that can reenter the contract. a. .trasnsfer() is preferred by us over .call() as its limited to 2300 gas. b. We do internal work in contracts prior to external calls. The safeguard is aligned to the Check Effects Interactions design pattern we use. For example in our function below, balances ie state are updated before the transfer."

It's best to not rely on the 2300 gas.

See: 
https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/

**Comment by MatricksDeCoder** [comment]
Noted and very interesting!
all transfer will be replaced with call e.g (bool success, ) = msg.sender.call.value(amount)("") and rely on Check Effects Interactions and Reentrancy Guards!

**Comment by MatricksDeCoder** [comment]
avoiding_common_attacks.md updated for the above
