### ISSUE TITLE
Update comments in Exchange.sol

### ISSUE THREAD

**Issue by tesla809** [MatricksDeCoder/Fojini-DEX#3]
Please update contract comments with natspec-format:
https://solidity.readthedocs.io/en/v0.4.21/layout-of-source-files.html#comments
https://docs.soliditylang.org/en/v0.5.10/natspec-format.html

**Comment by MatricksDeCoder** [comment]
Updated comments in Exchange.sol to be NatSpec format

**Comment by MatricksDeCoder** [comment]
change approved
