### ISSUE TITLE
Using Ownable.sol to restrict access

### ISSUE THREAD

**Issue by tesla809** [MatricksDeCoder/Fojini-DEX#5]
Good chance to use OpenZeppelin's Ownable.sol for restricting access:
https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/access

**Comment by MatricksDeCoder** [comment]
safer OpenZeppelin's Ownable.sol imported and used in Exchange.sol

**Comment by MatricksDeCoder** [comment]
change approved
